- name: Seafahrer
  hosts: tls_servers
  sudo: True
  user: root
  roles:
    - role: letsencrypt
      letsencrypt_webroot_path: /var/www/html
      letsencrypt_email: user@example.net
      letsencrypt_cert_domains:
        - www.example.net
        - example.net
      pre-tasks:
        - include: tasks/setup.yml
    - role: docker
  #post_tasks:
  #  - include: tasks/users.yml
  #  - include: tasks/nginx.yml
  #    tags:
  #      - nginx
  #  - include: tasks/htsp.yml

  #handlers:
  #  - name: systemctl daemon-reload
  #    command: systemctl daemon-reload 

  #  - include: roles/nginx/handlers/main.yml
  #  - include: roles/tomcat/handlers/main.yml
