- name: Seafahrer
  hosts: tls_servers
  sudo: True
  user: root
  pre_tasks:
    - include: tasks/setup.yml
  roles:
    - role: docker
    #- role: letsencrypt
    #  letsencrypt_webroot_path: /var/www/html
    #  letsencrypt_email: user@example.net
    #  letsencrypt_cert_domains:
    #    - www.example.net
    #    - example.net
  post_tasks:
    - include: tasks/images.yml
      tags:
        - docker
    - include: tasks/docker.yml
      tags:
        - docker
    - include: tasks/pip.yml
