- name: "app | build dir"
  file: path=/opt/{{application_name}} state=directory mode=0755

- name: "app | build files"
  template: src=templates/docker/app/Dockerfile.j2 dest=/opt/{{application_name}}/Dockerfile

- name: "app | app files"
  copy: src=files/docker/app/{{item}} dest=/opt/{{application_name}}/{{item}} force=yes
  with_items:
    - "{{application_name}}.jar"

- name: check or build image
  docker_image: >
    name="{{application_name}}/{{application_name}}"
    path="/opt/{{application_name}}/"
    state=build